language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

notifications:
  recipients:
    - bmukund@nuodb.com
    - bal.mukund4u@gmail.com
    
sudo: false

before_install:
  - ./test/mysql_setup.sh
  - ./test/nuodb_setup.sh

install: mvn -U clean install

script:
  - ./test/mysql_basic.sh
  - ./test/batch_test.sh

